### PR TITLE
APEX-132 #resolve added Apache copyright template for IntelliJ

### PR DESCRIPTION
**Pull request by vrozov**
@tweise, @PramodSSImmaneni please review

### CODE REVIEW

**Comment by tweise** [comment]
The issue of tracking files under the .idea folder is discussed in #102

Why to solve this on the IDE level when license:format will take care of it, not just for *.java but all file types?

**Comment by vrozov** [comment]
The template is not .java specific. It defines template and IntelliJ knows how to apply the template to different file types (properties, xml and etc).

Providing template fully automates inserting copyright notice into new files. All I need to do is to create new java class (or properties or xml file) in IntelliJ and the copyright is inserted automatically.

**Comment by tweise** [comment]
The source of truth is license:format, including the exclusions. And license:check will be part of the CI. Are you sure you can replicate all of that for IntelliJ?

**Comment by vrozov** [comment]
It was not meant to replace license:format or license:check. The purpose of the template is to help automate adding copyright notice to new .java/.xml/.properties and other files supported by IntelliJ.

If I understand correctly copyright should not be applied only to files that don't have any intellectual value, most likely such files are automatically generated and don't require editing by developers in IDE.

**Pull request merged**
