### PR TITLE
Fix download link in README.md

### PR DESCRIPTION
**Pull request by tweise**
@davidyan74 review

### CODE REVIEW

**Comment by vrozov** [comment]
Commit as Apex Dev?

**Comment by tweise** [comment]
Why?

**Comment by vrozov** [comment]
The commit fixes URL from one existing link to another.

**Comment by tweise** [comment]
I don't see why that matters. What you are suggesting is for automated changes (like formatting and release process), not for fixing bugs.

**Comment by vrozov** [comment]
Not necessarily they are limited to automated changes: https://github.com/apache/apex-core/commit/ec03f12cd0f1b9994a878237ca649d4c4a9c0423

**Comment by tweise** [comment]
There has been a discussion about this a while ago and the guidelines have been updated. Automatic changes (or those that are purely mechanical and could have been automatic should be attributed accordingly). You can find more old examples that predate this and don't comply. For this case, I cannot think of a smart script that would have generated the diff.

**Comment by vrozov** [comment]
IMO, it falls into "similar" qualification in "If commits result from running scripts, file formatting or _similar_, use following attribution: git commit --amend --author "Apex Dev <dev@apex.apache.org>". It is a _mechanical_ change from one URL to another.

I am -0 on the commit, meaning that I will not stop another committer from merging the change in. Once the same commit is done as Apex Dev, it will change to +1 and I will merge it in.

**Comment by tweise** [comment]
I disagree with your interpretation and the use of semi-anonymous author for such changes. It obfuscates the revision history which is there to tell others who has made a change. The exception in the contributor guidelines is for situations where the author information would be misleading (see code reformat and "similar").

While we are at it, I also don't think that #449 should be committed the way it is.

**Comment by vrozov** [comment]
IMO revision history gets obfuscated each time a semi-anonymous commit is done. In cases of a code reformat or changes made by a tool (script, IDE) there is still human/author behind the changes (somebody should run the script and/or review changes). If we all agree that those changes are semi-anonymous, changes similar to this PR or PR #449 (done by IntelliJ IDE) should be semi-anonymous as well.

**Comment by davidyan74** [comment]
I don't think who the author of the commit is matters much in this case. Let's not stall the process for this issue.

**Pull request merged**
