### PR TITLE
APEXCORE-304 Added support for class to classpath via populateDAG.

### PR DESCRIPTION
**Pull request by chinmaykolhatkar**
Added unit test for classpath check for StramClient
Added support for adding class to classpath for local mode.
Added unit test for classpath check for Local mode.

### CODE REVIEW

**Comment by chinmaykolhatkar** [comment]
This is continuation of pull request: https://github.com/apache/incubator-apex-core/pull/208

**Comment by chinmaykolhatkar** [comment]
Hello @vrozov @tweise Can this be merged if there are no further comments?

Thanks.

**Comment by tweise** [comment]
@chinmaykolhatkar Did not have a chance to look at it yet.

**Comment by chinmaykolhatkar** [comment]
Closing this PR and more changes are required. Will reopen a new one.

**Pull request closed without merging**
