### PR TITLE
APEXCORE-736 Using YARN client api to fetch the application master container report

### PR DESCRIPTION
**Pull request by pramodin**
This is a continuation of the PR https://github.com/apache/apex-core/pull/534 and merging this should close that PR.

### CODE REVIEW

**Review by vrozov — COMMENTED** [review]
squash commits

**Comment by pramodin** [comment]
The original change is from @devtagare hence the separate commits

**Comment by tweise** [comment]
rebase the commit and add closes #534 to the commit message

**Comment by pramodin** [comment]
@tweise does that close PRs, thought it was for github issues

**Comment by vrozov** [comment]
@devtagare Will you be OK if the @PramodSSImmaneni commit is squashed to your commit?

**Comment by devtagare** [comment]
Should be fine. Please go ahead .

**Comment by vrozov** [comment]
@PramodSSImmaneni Please rebase against upstream/master

**Pull request merged**
