### PR TITLE
Fix for Stram web service calls failing in secure non-HA mode for devel-3 branch

### PR DESCRIPTION
**Pull request by pramodin**
Fix for property name used to lookup RM webapp address in non-HA mode and additional log statements to help with debugging the request processing in future.

### CODE REVIEW

**Comment by pramodin** [comment]
@tweise see

**Comment by tweise** [comment]
Test failure unrelated: https://malhar.atlassian.net/browse/APEX-158

**Comment by tweise** [comment]
@PramodSSImmaneni Flattened to single commit and pushed, please close this PR.

**Comment by pramodin** [comment]
Thomas I think when there are review comments we can keep multiple commits.

**Comment by tweise** [comment]
I think they should be combined when the review comments were addressed, just like they would when submitting a patch.

**Comment by pramodin** [comment]
It would keep a record of the review.

**Pull request closed without merging**
