### PR TITLE
APEXCORE-415 #resolve #comment Fixed double checkpointing bug in Inpu…

### PR DESCRIPTION
**Pull request by ilooner**
…tNode.

### CODE REVIEW

**Comment by ilooner** [comment]
@PramodSSImmaneni  please review

**Comment by ilooner** [comment]
Travis failure unrelated to my change. All tests pass on my local machine

**Comment by ilooner** [comment]
@davidyan74 Please review

**Comment by davidyan74** [comment]
@ilooner Does this only happen in the InputNode? How about overriding the checkpoint() method in the InputNode for setting and checking for lastCheckpointWindowId without modifying the rest of the code? Something like: 

``` java
  @Override
  void checkpoint(long windowId)
  {
    if (lastCheckpointWindowId < currentWindowId) {
      super.checkpoint();
      lastCheckpointWindowId = currentWindowId;
    }
  }
```

**Comment by pramodin** [comment]
@davidyan74 I think this check happens for other nodes but is not happening for InputNode

**Comment by ilooner** [comment]
@davidyan74 There was a similar bug in Generic Node which I fixed and got merged before. The problem happens when The Operator CheckpointWindowCount is a multiple of the Dag CheckpointWindowCount. In that case the operator is checkpointed on receiving the endWindow tuple and the checkpoint tuple for the same window. When that happens AsyncFSStorageAgent throws an exception because there are two threads trying to move the same file.

**Comment by davidyan74** [comment]
@ilooner @PramodSSImmaneni  I see. Then shouldn't this change be in Node?

**Comment by sandeshh** [comment]
How about having the flag in CheckPoint function which decides whether to overwrite the existing checkpoints or not ?

**Comment by pramodin** [comment]
@ilooner Change looks good, can you add a test.

**Comment by pramodin** [comment]
@davidyan74 Will need a lot more refactoring to handle in Node as control tuples are being processed in the specific Node types.

**Comment by ilooner** [comment]
@PramodSSImmaneni will add test

**Comment by pramodin** [comment]
@sandeshh as @ilooner mentioned this shouldn't be happening in the first place so I don't think we would need a flag

**Comment by sandeshh** [comment]
@PramodSSImmaneni I am for having both the changes in.

**Comment by ilooner** [comment]
@PramodSSImmaneni @davidyan74  I have added tests. @davidyan74 I don't think your suggestion would work because it does not account for the ProcessMode and doCheckpoint variable interactions. I would like to maintain the same pattern for handling this corner case as existed previously in order to avoid unintended bugs. The code can be refactored down the road after more tests and documentation are introduced.

**Comment by davidyan74** [comment]
@ilooner OK

**Pull request merged**
