### PR TITLE
APEXCORE-566 Computing bufferServerBytes in the LogicalOperatorInfo

### PR DESCRIPTION
**Pull request by francisf**
@bhupeshchawda Please review.

### CODE REVIEW

**Review by bhupeshchawda — COMMENTED** [review]
Looks good. Can you add a unit test?

**Comment by francisf** [comment]
Done.

Thanks,
Francis

**Comment by vrozov** [comment]
IMO, it is questionable how useful total number of bytes/s emitted/consumed by an operator metric is. It will be more useful to provide such metric for each logical operator port.

**Comment by francisf** [comment]
Looping in @sashadt

**Pull request closed without merging**
