### PR TITLE
APEXCORE-522 - Promote singleton usage pattern for String2String, Long2String and other StringCodecs

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by vrozov** [comment]
retest this please

**Comment by vrozov** [comment]
@tweise Please review

**Comment by vrozov** [comment]
@tweise Please review

**Comment by vrozov** [comment]
@tushargosavi Please review

**Comment by tushargosavi** [comment]
@vrozov, I will review it

**Comment by tushargosavi** [comment]
looks fine to me, I will merge it shortly.

**Pull request merged**
