### PR TITLE
APEXCORE-405 Example application showing how to use the launcher API in a project

### PR DESCRIPTION
**Pull request by pramodin**
@tweise this is an example showing launcher API usage (which I had earlier in my repo). I felt that the best place would be to include it in apex itself as an example since it focuses on the API usage rather than application functionality that malhar focuses on.

### CODE REVIEW

**Comment by tweise** [comment]
@PramodSSImmaneni I think this example is a bit confusing, as it still builds a .apa file, while the direct launch support is really a way to avoid that and facilitate a different deployment process.

**Comment by pramodin** [comment]
@tweise removed apa generation, it's now a normal java project with exec plugin to launch the app, instruction in README.

**Comment by sandeshh** [comment]
Should this be in Malhar?

**Comment by pramodin** [comment]
Could be. Since it's objective is to show the use of an api and not necessarily an application or an operator, I was thinking this may be a good place to put it.

**Comment by tweise** [comment]
+1 for moving it to Malhar, once the core version there is upgraded.

**Comment by vrozov** [comment]
@PramodSSImmaneni @tweise closed due to inactivity

**Pull request closed without merging**
