### PR TITLE
APEXCORE-426 Reuse the running container, when the Stram restarts.

### PR DESCRIPTION
**Pull request by sandeshh**
@tweise, @vrozov, @PramodSSImmaneni, @davidyan74 please review

If you guys are fine with the approach, I will work on unit tests.

### CODE REVIEW

**Comment by pramodin** [comment]
started looking at it

**Comment by tushargosavi** [comment]
@sandeshh what do I need to test this feature. I would like test it more.

**Comment by sandeshh** [comment]
@tushargosavi kill the AppMaster and verify the container ids of the child containers before and after, they should not change. New app master should start communicating with child containers correctly.

**Comment by pramodin** [comment]
@sandeshh what happens if there is a container failure before the stram is operational or has received heartbeats from that container?

**Comment by sandeshh** [comment]
@PramodSSImmaneni 
NodeManager and ResourceManager both can inform about the container failure to Stram. If they inform Stram after recovery then Stram will restart the containers otherwise, Stram will wait till the heartbeat timeout before restarting the container.

**Comment by tweise** [comment]
@sandeshh please document the test scenarios in the JIRA.

**Comment by sandeshh** [comment]
@tweise done.

**Comment by vrozov** [comment]
@tweise @PramodSSImmaneni Will it be useful to have an option to force old behavior? I don't see why such option is needed, do you?

**Comment by tweise** [comment]
I don't think so either.

**Comment by sandeshh** [comment]
@vrozov I have rebased it, please merge.

**Comment by pramodin** [comment]
Just for completeness can you explain on the JIRA what happens if there were plan changes that were saved but before stram could affect them it got shutdown. Will the new instance make those changes.

**Comment by sandeshh** [comment]
@PramodSSImmaneni done.
https://issues.apache.org/jira/browse/APEXCORE-426

**Pull request merged**
