### PR TITLE
Fixing cleanup during shutdown to avoid intermittent errors

### PR DESCRIPTION
**Pull request by pramodin**
Was getting intermittent test failures with partitioning test. In debugging noticed the following cleanup problem. Not seeing the test failures anymore but not sure if this fixed it. Will be on the lookup. @tweise please see

### CODE REVIEW

**Comment by pramodin** [comment]
@tweise please take a look when you have time

**Comment by pramodin** [comment]
Considered using executors but since it is a thread per container, there is no reuse and we probably want container id in the thread name keeping track of the threads directly

**Comment by tweise** [comment]
Looks good. Please squash and rebase.

**Comment by pramodin** [comment]
@tweise done

**Pull request merged**
