### PR TITLE
APEXCORE-715 Remove unnecessary @Evolving annotation in engine

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by pramodin** [comment]
LGTM

**Review by bhupeshchawda — APPROVED** [review]
LGTM

**Comment by pramodin** [comment]
Please add some javadoc at top level for *.api packages that these interfaces can change as they are internal api and it is use it at your own risk.

**Comment by pramodin** [comment]
I have put that into a separate JIRA as this JIRA is focussed on annotation.

**Comment by vrozov** [comment]
Agree, I think that adding javadoc at the top level for *.api packages in the engine will help to avoid any confusion regarding stability and the audience of the "api". It can and should be done as a separate JIRA/PR.

**Pull request merged**
