### PR TITLE
Bumped minimum maven version to 3.0.5. Split enforcer executions by enforced rule.

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by 243826** [comment]
Vlad, I thought the verbosity of the build was reduced to info? Travis log is huuuuuge.

**Comment by vrozov** [comment]
@243826 Chetan, it was only done for release 3.2 and up. The fix is not in release 3.1 branch. I will open a separate pull request for this release.

**Comment by tweise** [comment]
Why is that logging change needed in the 3.1 branch? The release branches are for patches that address critical issues. Unit test log level does not seem to fit into the category.

**Comment by vrozov** [comment]
The change is needed for Travis CI. Without the logging level change test fails due to amount of output.

**Comment by tweise** [comment]
Travis fails for different reason:

```
Results :

Failed tests: 
  AutoMetricTest.testMetricsAnnotatedMethod:382 myMetric expected:<3> but was:<0>
  AutoMetricTest.testMetricsAggregations:279 progress expected:<2> but was:<1>

Tests run: 247, Failures: 2, Errors: 0, Skipped: 10
```

Build for previous PR passed:

https://travis-ci.org/apache/incubator-apex-core/builds/87812654

@chandnisingh Some of the unit tests need to be looked into.

**Comment by vrozov** [comment]
Travis CI fails build when log reaches 4 MB in size assuming that tests hangs. Without changing log level it is very close to the limit at 3.8 MB.

**Comment by tweise** [comment]
I see intermittent test failures on the local environment also, unrelated to Travis.

**Comment by vrozov** [comment]
Those are caused by flaky unit tests and are not related to the log size limit. Travis CI builds may fail for any of these reasons.

**Pull request merged**
