### PR TITLE
Refactored monolithic deployInputStream function

### PR DESCRIPTION
**Pull request by ilganeli**
In an effort to better understand the flow of data within Apex, I have refactored the monolithic (200+ line long) deployInputStreams function to modularize it, add comments, and clarify operational flow.
This patch also includes formatting fixes per CodeStyle/CheckStyle guidelines for existing code.

I would very much appreciate a review to confirm that method and variable names make sense and that comments appropriately capture what's going on. There has not been any modification of code (with the exception of duplicate instantiation of `streamCodecIdentifier`, `streamCodec`, `sinkIdentifer`, and `sourceIdentifier` in `connectInputToBufferServer` and `connectInputToLocalSink`. This was done for the sake of more concise method declaration. All other changes only involved method extraction.

### CODE REVIEW

**Comment by pramodin** [comment]
Ilya can you squash them to a single commit

**Comment by ilganeli** [comment]
Pramod, do you want all the commits to be a single commit or do you just want the style fixes as a single commit?

**Comment by tweise** [comment]
I would prefer to see style related changes as separate PR and net changes for original topic combined into single commit (with JIRA reference).

**Comment by ilganeli** [comment]
I'll submit a second PR.

**Pull request closed without merging**
