### PR TITLE
APEX-253 #resolve changed malhar dependency from com.datatorrent to org.apache.apex

### PR DESCRIPTION
**Pull request by davidyan74**

### CODE REVIEW

**Comment by davidyan74** [comment]
@tweise please review

**Comment by cnauroth** [comment]
Hi @davidyan74 .  This looks good to me.  While you're in here, would it also make sense to remove the mention of DataTorrent in the comment about "different version of DataTorrent" in the `properties` section?  How about also renaming the `datatorrent.apppackage.classpath` property?

**Comment by davidyan74** [comment]
@cnauroth thanks for your suggestion. done.

**Comment by cnauroth** [comment]
+1 from me.  Thanks, @davidyan74 !

**Pull request merged**
