### PR TITLE
APEXCORE-630 Removing FastDataList as it is not complete and not deve…

### PR DESCRIPTION
**Pull request by sandeshh**
…loped, so no reason to keep it

@vrozov please review.

### CODE REVIEW

**Comment by vrozov** [comment]
There are few outstanding PR like #436  and #445 that conflicts with this PR. Please wait for the outstanding PR to be merged or closed.

**Comment by pramodin** [comment]
I would like to understand the motivation behind the FastDataList and the optimizations that are in there before we remove it. There may be something that is useful that we can either blend in or use. I was interested to know what it did but didn't get a chance earlier. I would like to spend some time to understand it. Can you hold off on this till then?

**Comment by vrozov** [comment]
@PramodSSImmaneni The code for FastDataList is in the git and the history is preserved. IMO, there is no need to keep it around till design rationalle behind FastDataList is clear. The current implementation is not complete and the design is not clear.

@sandeshh Please revert back all changes in the DataList and keep `protected` as is. This will allow to introduce FastDataList or any other variations of DataList without modifying DataList again. I don't see why making variables `private` will make a big difference.

**Comment by sandeshh** [comment]
@vrozov will make the required changes.

**Comment by pramodin** [comment]
Is it putting an undue burden on the development of new features, fixing bugs or maintainability of other code by being present? Why not leave it in its current state and look into improving it later.

**Comment by vrozov** [comment]
Yes, it does. There are several occurrences of code changes that also required modifications to the FastDataList (for example #445) and there will be more such cases with the introduction of netty and in memory publishers. This functionality is not well understood, not used, not maintained and is not tested. It's hard to say whether it still works or not as it was not maintained and used for a long time. It is necessary to understand the design rationale behind the class or remove it.

**Comment by pramodin** [comment]
Are the changes required so far to FastDataList trivial or substantial, for example I would put #445 in the former category.

**Comment by vrozov** [comment]
Yes, they are trivial and could (and IMO, should) be avoided. It is not clear whether FastDataList will work with the back pressure and whether or not FastDataList still works.

**Comment by sandeshh** [comment]
@vrozov I have made the required changes.
@PramodSSImmaneni We can keep a jira open to analyze the FastDataList and remove it from the code.

**Comment by sandeshh** [comment]
@vrozov all the conflicting PRs are merged. I have rebased the PR. Please merge.
@PramodSSImmaneni let me know your take.

**Comment by pramodin** [comment]
I am not in favor of removing something without understanding what it is trying to do and if there is anything there that can be useful to us.

**Comment by sandeshh** [comment]
@PramodSSImmaneni are you fine if we keep the jira open?

**Pull request closed without merging**
