### PR TITLE
APEXCORE-267 #resolve #comment fixing checkstyle violations in API

### PR DESCRIPTION
**Pull request by otterc**
@vrozov please review and merge

### CODE REVIEW

**Comment by tweise** [comment]
Looks like other changes are part of the commit due to squash?

**Comment by otterc** [comment]
Something weird is happening. When I make the commit from my id, then the commit consists of correct files however when I change the author to "jenkins@datatorrent", it is adding additional changes.

**Comment by otterc** [comment]
@tweise @vrozov fixed the commit. please review.

**Comment by otterc** [comment]
squashed the commits.

**Pull request merged**
