### PR TITLE
APEX-184

### PR DESCRIPTION
**Pull request by vrozov**
1. In autoFlushExecutor don't exit run() until there is at least one listener that has more data to send.
2. Do not enable read in resumeReadIfSuspended when not able to switch to a new buffer.
3. Fix possible race condition in Block acquire.
4. Fix for incorrect counting of in memory block permits.
5. Fix check style violations.

@243826, @PramodSSImmaneni, @ilooner please review.

### CODE REVIEW

**Comment by vrozov** [comment]
I need to add few more changes to the pull request. Please don't merge it in.

**Comment by vrozov** [comment]
The latest changes are in, please review.

**Comment by PramodSSImmaneni** [comment]
Any reason you did the checkstyle for the lines you didnt modify, was it your IDE automatically changing them.

**Comment by pramodin** [comment]
Looking at it

**Comment by pramodin** [comment]
Vlad can you back out the pure formatting changes wherever there are no new code changes, for example Server has many changes like this. If there are a few lines related to your code changes you can change the formatting, for example if you have changes only in the "if" you can still fix formatting for the else.

**Pull request merged**
