### PR TITLE
APEXCORE-741 Upgrade netlet dependency to 1.3.1

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by pramodin** [comment]
Looks good to me. I will merge it if there are no objections.

**Comment by tweise** [comment]
@vrozov can you take a look at the following exceptions in the malhar CI log and see if theses should be suppressed?
```
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
	at com.datatorrent.netlet.WriteOnlyClient.channelWrite(WriteOnlyClient.java:187)
	at com.datatorrent.netlet.WriteOnlyLengthPrependerClient.write(WriteOnlyLengthPrependerClient.java:75)
	at com.datatorrent.netlet.Listener$DisconnectingListener.write(Listener.java:241)
	at com.datatorrent.netlet.DefaultEventLoop.handleSelectedKey(DefaultEventLoop.java:380)
	at com.datatorrent.netlet.OptimizedEventLoop$SelectedSelectionKeySet.forEach(OptimizedEventLoop.java:59)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:192)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:157)
	at com.datatorrent.netlet.DefaultEventLoop.run(DefaultEventLoop.java:171)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vrozov** [comment]
@tweise Do you suggest to suppress them in netlet, apex or malhar unit tests?

**Comment by tweise** [comment]
I'm looking for your recommendation. If it can be handled in core then it would avoid potentially repeated work downstream.

**Comment by vrozov** [comment]
I don't think that core can blindly suppress the exception, it can't distinguish actually broken connection from a connection that was terminated while tearing down. To be able to handle the case on the apex side, it would be necessary to revisit buffer server client disconnect protocol.

**Comment by pramodin** [comment]
Looks like the discussion wouldn't have an impact on this particular PR, will merge it.

**Comment by pramodin** [comment]
Can you rebase

**Comment by vrozov** [comment]
Done

**Pull request merged**
